# Generated by Django 3.2.13 on 2022-05-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220519_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='actors', to='movie.Actor', verbose_name='актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='movie.Genre', verbose_name='жанры'),
        ),
    ]
